def registro():
    estudiantes={}
    Prom={}
CantMayor = 0

NoEstudiantes = int(input("Por favor ingrese la cantidad de alumnos: "))
    
for i in range(NoEstudiantes):
        Nombre = input("Ingrese el nombre del estudiante: ")
        notascant = int(input("Por favor ingrese la cantidad de notas: "))
        Prom=0
        for x in range(notascant):
            Notas = int(input("Por favor ingrese la notas de los estudiantes: "))
        if Notas > CantMayor:
             Notas == CantMayor

        